### ISSUE TITLE
jsondecode error bug or something

### ISSUE THREAD

**Issue by mobilegaming08** [AlexFlipnote/TalkSimulator#1]
I'm not sure if I'm doing it right as the changes I only made are config.json itself filling out the needed parts but I get this at the end on why it isn't running:
json.decoder.JSONDecodeError: Expecting value: line 3 column 14 (char 87)

Thanks in advance though.

**Comment by AlexFlipnote** [comment]
This means that you've messed something up in the config.json at line 3, column 4.
I recommend using some sort of text editor with JSON checker to see your problem, personally I use atom.io

**Comment by mobilegaming08** [comment]
Okay. I found the problem. I realized that UserID: and ChannelID had to remove as it is why it won't work so I did remove it and it finally works now, thanks for correcting me on that. I'll go ahead and close this issue now.
